### ISSUE TITLE
Нужно перевести все каналы в слак или гиттер, так как в России к телеграм уже нельзя подключиться 

### ISSUE THREAD

**Issue by EndyKaufman** [Angular-RU/angular-ru.github.io#3]

**Comment by obenjiro** [comment]
Нет необходимости. Telegram прекрасно работает через VPN. 

решения:
— http://opentg.us
— http://fuckrkn.us
— http://telegram.veesecurity.com
— https://tgvpn.com/ru
— https://t.me/socks?server=telegram.vpn99.net&port=55655
— http://12345.fuckrkn.us
— http://12345.opentg.us


https://www.google.nl/amp/s/m.wikihow.com/Use-a-VPN%3famp=1

**Comment by vadjs** [comment]
Телеграм прекрасно работает и без VPN, так что данные решения пока что не нужны.

**Comment by splincode** [comment]
Согласен, для веб версии есть куча экстеншинов с настроенной проксей, а в мобильной версии нормально можно поставить прокси

Я думаю, тот кому надо все сделает...
